server:
    port: 8080

spring:
    application:
        name: todoapp
    datasource:
        url: jdbc:h2:mem:testdb
        driver-class-name: org.h2.Driver
        username: ${SPRING_DATASOURCE_H2_USERNAME}
        password: ${SPRING_DATASOURCE_H2_PASSWORD}
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true